### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblvideo#7]
``` 
(dlcenv) cyrille@carves:~/git/iblvideo (master)$ python -c "from iblvideo.run import run_queue; run_queue(machine='cyrille', n_sessions=1)"
Connected to https://alyx.internationalbrainlab.org as cyrille
Downloading: /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/_iblrig_bodyCamera.raw.c0976e9d-f1cc-497d-bc2b-694be4293071.mp4 Bytes: 1628041371
Downloading: /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/_iblrig_leftCamera.raw.cbb8aa71-bf77-434a-815f-ccd9f4a738ba.mp4 Bytes: 11439252596
Downloading: /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/_iblrig_rightCamera.raw.025d5ca4-263e-48cc-9ddd-aa289cf47369.mp4 Bytes: 5140485654
2021-03-22 15:39:16.185 INFO     [tasks.py:68] Starting job <class 'iblvideo.run.TaskDLC'>████████████| 100.0% 
2021-03-22 15:39:16.185 INFO     [run.py:28] Running on cyrille
2021-03-22 15:39:16.186 INFO     [run.py:31] Running DLC on 3 video files.
2021-03-22 15:39:16.248 INFO     [choiceworld.py:131] STEP 01 Generating sparse frame video /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4 for posture detection
2021-03-22 15:40:59.2 INFO     [choiceworld.py:153] STEP 01 STOP Generating sparse frame video /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4 for posture detection
2021-03-22 15:40:59.6 INFO     [choiceworld.py:163] STEP 02 START Posture detection /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4
Using snapshot-1030000 for model /home/cyrille/ephys/FlatIron/resources/dlc/weights_v0.1/roi_detect-2019-12-11/dlc-models/iteration-0/roiDec11-trainset95shuffle1
Initializing MobileNet
2021-03-22 15:41:00.577401: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-03-22 15:41:00.597831: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3299990000 Hz
2021-03-22 15:41:00.598632: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5614eac5d6f0 executing computations on platform Host. Devices:
2021-03-22 15:41:00.598654: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2021-03-22 15:41:00.697895: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5614ec8c4210 executing computations on platform CUDA. Devices:
2021-03-22 15:41:00.697943: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2070 SUPER, Compute Capability 7.5
2021-03-22 15:41:00.698158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2070 SUPER major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:65:00.0
totalMemory: 7.79GiB freeMemory: 6.50GiB
2021-03-22 15:41:00.698194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2021-03-22 15:41:00.699217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-22 15:41:00.699239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2021-03-22 15:41:00.699251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2021-03-22 15:41:00.699354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6319 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070 SUPER, pci bus id: 0000:65:00.0, compute capability: 7.5)
Starting to analyze %  /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4
/home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw  already exists!
Loading  /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4
Duration of video [s]:  100.0 , recorded with  5.0 fps!
Overall # of frames:  500  found with (before cropping) frame dimensions:  1280 1024
Starting to extract posture
  0%|                                                                                                                                                                                                                                                                                                 | 0/500 [00:00<?, ?it/s]2021-03-22 15:41:02.163482: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2021-03-22 15:41:02.165054: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
2021-03-22 15:41:02.205 INFO     [choiceworld.py:168] STEP 02 END Posture detection /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4
INFO:ibllib:STEP 02 END Posture detection /home/cyrille/ephys/FlatIron/cortexlab/Subjects/KS043/2020-12-09/001/raw_video_data/dlc_tmp_iblrig_leftCamera.raw/_iblrig_leftCamera.subsampled.mp4
2021-03-22 15:41:02.206 ERROR    [tasks.py:76] Traceback (most recent call last):
  File "/home/cyrille/git/iblvideo/dlcenv/lib/python3.7/site-packages/ibllib/pipes/tasks.py", line 73, in run
    self.outputs = self._run(**kwargs)
  File "/home/cyrille/git/iblvideo/iblvideo/run.py", line 35, in _run
    dlc_result = dlc(files_mp4[cam], path_dlc)
  File "/home/cyrille/git/iblvideo/iblvideo/choiceworld.py", line 320, in dlc
    df_crop = _s02_detect_rois(tdir, file_sparse, dlc_params)   # GPU dlc
  File "/home/cyrille/git/iblvideo/iblvideo/choiceworld.py", line 169, in _s02_detect_rois
    file_out = pd.read_hdf(h5_sub)
  File "/home/cyrille/git/iblvideo/dlcenv/lib/python3.7/site-packages/pandas/io/pytables.py", line 387, in read_hdf
    "Support for generic buffers has not been implemented."
NotImplementedError: Support for generic buffers has not been implemented.
ERROR:ibllib:Traceback (most recent call last):
  File "/home/cyrille/git/iblvideo/dlcenv/lib/python3.7/site-packages/ibllib/pipes/tasks.py", line 73, in run
    self.outputs = self._run(**kwargs)
  File "/home/cyrille/git/iblvideo/iblvideo/run.py", line 35, in _run
    dlc_result = dlc(files_mp4[cam], path_dlc)
  File "/home/cyrille/git/iblvideo/iblvideo/choiceworld.py", line 320, in dlc
    df_crop = _s02_detect_rois(tdir, file_sparse, dlc_params)   # GPU dlc
  File "/home/cyrille/git/iblvideo/iblvideo/choiceworld.py", line 169, in _s02_detect_rois
    file_out = pd.read_hdf(h5_sub)
  File "/home/cyrille/git/iblvideo/dlcenv/lib/python3.7/site-packages/pandas/io/pytables.py", line 387, in read_hdf
    "Support for generic buffers has not been implemented."
NotImplementedError: Support for generic buffers has not been implemented.
2021-03-22 15:41:02.206 INFO     [tasks.py:77] Job <class 'iblvideo.run.TaskDLC'> errored
INFO:ibllib:Job <class 'iblvideo.run.TaskDLC'> errored
2021-03-22 15:41:02.206 INFO     [tasks.py:87] N outputs: 0
INFO:ibllib:N outputs: 0
2021-03-22 15:41:02.206 INFO     [tasks.py:88] --- 106.02092289924622 seconds run-time ---
INFO:ibllib:--- 106.02092289924622 seconds run-time ---
``` 
Nothing to do with pandas, the interesting bit is this:
```
2021-03-22 16:01:00.211021: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by oliche** [comment]
We checked:

- CUDA version matches CUDNN version
- GPU is not overloaded
- ran mnistCUDNN test successfully

In the end the fix was to set the following env variable
`export TF_FORCE_GPU_ALLOW_GROWTH='true'`

This is still puzzling as this GPU has 8Gb RAM.
